final/config/routes.rb
Rails.application.routes.draw do
  root:'welcome#index'
  get 'welcome/index'
  resources :boatcomments
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

final/app/models/boatcomment.rb
class Boatcomment < ApplicationRecord
end

final/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

final/app/controllers/boatcomments_controller.rb
class BoatcommentsController < ApplicationController
  before_action :set_boatcomment, only: [:show, :edit, :update, :destroy]

  # GET /boatcomments
  # GET /boatcomments.json
  def index
    @boatcomments = Boatcomment.all
  end

  # GET /boatcomments/1
  # GET /boatcomments/1.json
  def show
  end

  # GET /boatcomments/new
  def new
    @boatcomment = Boatcomment.new
  end

  # GET /boatcomments/1/edit
  def edit
  end

  # POST /boatcomments
  # POST /boatcomments.json
  def create
    @boatcomment = Boatcomment.new(boatcomment_params)

    respond_to do |format|
      if @boatcomment.save
        format.html { redirect_to @boatcomment, notice: 'Boatcomment was successfully created.' }
        format.json { render :show, status: :created, location: @boatcomment }
      else
        format.html { render :new }
        format.json { render json: @boatcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boatcomments/1
  # PATCH/PUT /boatcomments/1.json
  def update
    respond_to do |format|
      if @boatcomment.update(boatcomment_params)
        format.html { redirect_to @boatcomment, notice: 'Boatcomment was successfully updated.' }
        format.json { render :show, status: :ok, location: @boatcomment }
      else
        format.html { render :edit }
        format.json { render json: @boatcomment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boatcomments/1
  # DELETE /boatcomments/1.json
  def destroy
    @boatcomment.destroy
    respond_to do |format|
      format.html { redirect_to boatcomments_url, notice: 'Boatcomment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boatcomment
      @boatcomment = Boatcomment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boatcomment_params
      params.require(:boatcomment).permit(:user, :comment, :boat)
    end
end

final/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

final/app/helpers/application_helper.rb
module ApplicationHelper
end

final/app/helpers/boatcomments_helper.rb
module BoatcommentsHelper
end

final/app/helpers/welcome_helper.rb
module WelcomeHelper
end

final/app/views/boatcomments/_form.html.erb
<%= form_with(model: boatcomment, local: true) do |form| %>
  <% if boatcomment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(boatcomment.errors.count, "error") %> prohibited this boatcomment from being saved:</h2>

      <ul>
      <% boatcomment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user %>
    <%= form.text_field :user, id: :boatcomment_user %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :boatcomment_comment %>
  </div>

  <div class="field">
    <%= form.label :boat %>
    <%= form.text_field :boat, id: :boatcomment_boat %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

final/app/views/boatcomments/edit.html.erb
<h1>Editing Boatcomment</h1>

<%= render 'form', boatcomment: @boatcomment %>

<%= link_to 'Show', @boatcomment %> |
<%= link_to 'Back', boatcomments_path %>

final/app/views/boatcomments/index.html.erb
<p id="notice"><%= notice %></p>
<div class="marketing-site-content-section">
  <div class="marketing-site-content-section-img">
    <img src="https://images.pexels.com/photos/256046/pexels-photo-256046.jpeg?h=350&auto=compress&cs=tinysrgb" alt="" />
  </div>
  <div class="marketing-site-content-section-block">
    <h3 class="marketing-site-content-section-block-header">Yeti Snowcone Agency</h3>
    <p class="marketing-site-content-section-block-subheader subheader">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam omnis, maxime libero natus qui minus!</p>
    <a href="#" class="round button small">learn more</a>
  </div>
  <div class="marketing-site-content-section-block small-order-2 medium-order-1">
    <h3 class="marketing-site-content-section-block-header">Yeti Snowcone Agency</h3>
    <p class="marketing-site-content-section-block-subheader subheader">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aperiam omnis, maxime libero natus qui minus!</p>
    <a href="#" class="round button small">learn more</a>
  </div>
  <div class="marketing-site-content-section-img small-order-1 medium-order-2">
    <img src="https://images.pexels.com/photos/300857/pexels-photo-300857.jpeg?h=350&auto=compress&cs=tinysrgb" alt="" />
  </div>
</div>


<h1>Boatcomments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Comment</th>
      <th>Boat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boatcomments.each do |boatcomment| %>
      <tr>
        <td><%= boatcomment.user %></td>
        <td><%= boatcomment.comment %></td>
        <td><%= boatcomment.boat %></td>
        <td><%= link_to 'Show', boatcomment %></td>
        <td><%= link_to 'Edit', edit_boatcomment_path(boatcomment) %></td>
        <td><%= link_to 'Destroy', boatcomment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Boatcomment', new_boatcomment_path %>

final/app/views/boatcomments/new.html.erb
<h1>New Boatcomment</h1>

<%= render 'form', boatcomment: @boatcomment %>

<%= link_to 'Back', boatcomments_path %>

final/app/views/boatcomments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @boatcomment.user %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @boatcomment.comment %>
</p>

<p>
  <strong>Boat:</strong>
  <%= @boatcomment.boat %>
</p>

<%= link_to 'Edit', edit_boatcomment_path(@boatcomment) %> |
<%= link_to 'Back', boatcomments_path %>

final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

final/app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>